language: csharp
mono: none
dotnet: 2.2.401
solution: TorrentTitleParser.sln
script:
 - dotnet build --configuration Release
 - dotnet test TorrentTitleParser.Tests
deploy:
 skip_cleanup: true
 provider: script
 script: chmod +x ./deploypackage.sh && ./deploypackage.sh $NUGET_API_KEY $NUGET_SOURCE
 on:
  branch: master
  condition: '"x${NUGET_API_KEY}" != "x" && "x$NUGET_SOURCE" != "x"'