language: csharp
mono: none
dotnet: 2.2.401
env:
 global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
solution: TorrentTitleParser.sln
script:
 - dotnet build --configuration Release
 - dotnet test TorrentTitleParser.Tests
deploy:
 skip_cleanup: true
 provider: script
 script: chmod +x ./deploypackage.sh && ./deploypackage.sh $NUGET_API_KEY $NUGET_SOURCE
 on:
  branch: master
  condition: '"x${NUGET_API_KEY}" != "x" && "x$NUGET_SOURCE" != "x"'